/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    gebruikers: GebruikerAuthOperations;
  };
  blocks: {};
  collections: {
    producten: Producten;
    recepten: Recepten;
    ingredienten: Ingredienten;
    allergenen: Allergenen;
    'btw-tarieven': BtwTarieven;
    categorieen: Categorieen;
    seizoenen: Seizoenen;
    leveranciers: Leverancier;
    media: Media;
    klanten: Klanten;
    evenementen: Evenementen;
    materialen: Materialen;
    offertes: Offerte;
    orders: Order;
    facturen: Facturen;
    producties: Producty;
    inkopen: Inkopen;
    pickings: Picking;
    leveringen: Leveringen;
    gebruikers: Gebruiker;
    verzendlog: Verzendlog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    producten: ProductenSelect<false> | ProductenSelect<true>;
    recepten: ReceptenSelect<false> | ReceptenSelect<true>;
    ingredienten: IngredientenSelect<false> | IngredientenSelect<true>;
    allergenen: AllergenenSelect<false> | AllergenenSelect<true>;
    'btw-tarieven': BtwTarievenSelect<false> | BtwTarievenSelect<true>;
    categorieen: CategorieenSelect<false> | CategorieenSelect<true>;
    seizoenen: SeizoenenSelect<false> | SeizoenenSelect<true>;
    leveranciers: LeveranciersSelect<false> | LeveranciersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    klanten: KlantenSelect<false> | KlantenSelect<true>;
    evenementen: EvenementenSelect<false> | EvenementenSelect<true>;
    materialen: MaterialenSelect<false> | MaterialenSelect<true>;
    offertes: OffertesSelect<false> | OffertesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    facturen: FacturenSelect<false> | FacturenSelect<true>;
    producties: ProductiesSelect<false> | ProductiesSelect<true>;
    inkopen: InkopenSelect<false> | InkopenSelect<true>;
    pickings: PickingsSelect<false> | PickingsSelect<true>;
    leveringen: LeveringenSelect<false> | LeveringenSelect<true>;
    gebruikers: GebruikersSelect<false> | GebruikersSelect<true>;
    verzendlog: VerzendlogSelect<false> | VerzendlogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    bedrijfsinstellingen: Bedrijfsinstellingen;
  };
  globalsSelect: {
    bedrijfsinstellingen: BedrijfsinstellingenSelect<false> | BedrijfsinstellingenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Gebruiker;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface GebruikerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Het verkoopbare item dat in de Foodbook getoond wordt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producten".
 */
export interface Producten {
  id: number;
  naam: string;
  beschrijving?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categorie: number | Categorieen;
  /**
   * Sleep om te herordenen; de eerste foto is de hoofdfoto.
   */
  fotos?: (number | Media)[] | null;
  /**
   * Moet onderdeel zijn van de fotolijst hierboven.
   */
  hoofdfoto?: (number | null) | Media;
  portiesBasis: number;
  eenheid: 'gram' | 'ml' | 'stuk' | 'kg' | 'liter';
  /**
   * Het veld dat de rekenmotor schaalt. Een wijziging werkt door op open evenementen, nooit op al verzonden offertes of facturen.
   */
  hoeveelheidPerPersoon: number;
  recept?: (number | null) | Recepten;
  prijsPerPersoon: number;
  btwTarief: number | BtwTarieven;
  /**
   * Alleen voor artikelen zonder recept. De allergenen uit het recept worden automatisch toegevoegd.
   */
  allergenen?: (number | Allergenen)[] | null;
  /**
   * Uit = verborgen in de Foodbook, niet verwijderd.
   */
  actief?: boolean | null;
  seizoen?: (number | null) | Seizoenen;
  /**
   * Materialen die standaard bij dit gerecht horen, gerekend naar het aantal gasten. Eén bord per gast is 1 per 1; één warmhoudplaat per 50 gasten is 1 per 50. Per evenement kan dit later handmatig worden aangevuld.
   */
  materialen?:
    | {
        materiaal: number | Materialen;
        hoeveelheid: number;
        /**
         * Laat op 1 staan voor "per gast".
         */
        perAantalGasten: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorieen".
 */
export interface Categorieen {
  id: number;
  naam: string;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload meerdere foto’s tegelijk, sleep om te herordenen, kies een hoofdfoto. Bijsnijden en verkleinen gebeurt automatisch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijft de foto voor toegankelijkheid, en is herbruikbaar als de Foodbook ooit als webpagina verschijnt.
   */
  altTekst: string;
  /**
   * Bepaalt de volgorde binnen het product.
   */
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'foodbook-card'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'foodbook-hero'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    print?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recepten".
 */
export interface Recepten {
  id: number;
  naam: string;
  /**
   * Aantal porties waarvoor dit recept geschreven is, bv. 10.
   */
  basisPorties: number;
  /**
   * De portiegrootte waarop de regels hieronder zijn gebaseerd. De rekenmotor gebruikt dit als ijkpunt.
   */
  hoeveelheidPerPersoon: number;
  eenheid: 'gram' | 'ml' | 'stuk' | 'kg' | 'liter';
  /**
   * Hoeveelheden voor het volledige recept, niet per persoon.
   */
  ingredienten: {
    ingredient: number | Ingredienten;
    hoeveelheid: number;
    eenheid: 'gram' | 'ml' | 'stuk' | 'kg' | 'liter';
    id?: string | null;
  }[];
  bereidingswijze?: string | null;
  kooktijdMinuten?: number | null;
  /**
   * Groepeert de regels op de productielijst, bv. "Warme keuken".
   */
  keukenstation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * De bron van waarheid voor allergenen en inkoopprijzen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredienten".
 */
export interface Ingredienten {
  id: number;
  naam: string;
  inkoopeenheid: 'gram' | 'ml' | 'stuk' | 'kg' | 'liter';
  /**
   * Prijs per één inkoopeenheid, exclusief btw.
   */
  inkoopprijs: number;
  leverancier?: (number | null) | Leverancier;
  /**
   * Op ingrediëntniveau vastleggen; de allergenen van recepten en producten volgen hieruit.
   */
  allergenen?: (number | Allergenen)[] | null;
  houdbaarheidDagen?: number | null;
  /**
   * In de inkoopeenheid. Wordt afgetrokken van de inkoopbehoefte.
   */
  voorraad?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leveranciers".
 */
export interface Leverancier {
  id: number;
  naam: string;
  contactpersoon?: string | null;
  email?: string | null;
  telefoon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * De wettelijke allergenenlijst. Wijzigt zelden; alleen de beheerder beheert deze.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergenen".
 */
export interface Allergenen {
  id: number;
  naam: string;
  /**
   * Code voor audit-traceerbaarheid, bv. GLUTEN.
   */
  wettelijkeCode: string;
  icoon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catering is doorgaans 9%, alcohol en enkele artikelen 21%.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "btw-tarieven".
 */
export interface BtwTarieven {
  id: number;
  naam: string;
  /**
   * Vul 9 of 21 in, niet 0,09.
   */
  percentage: number;
  /**
   * Vooraf ingevuld bij een nieuw product.
   */
  standaard?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seizoenen".
 */
export interface Seizoenen {
  id: number;
  naam: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Niet-voedsel: borden, bestek, linnen, chafing dishes, transportkratten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materialen".
 */
export interface Materialen {
  id: number;
  naam: string;
  eenheid: 'gram' | 'ml' | 'stuk' | 'kg' | 'liter';
  /**
   * v1: alleen deze vlag; volledig voorraadbeheer is fase 2.
   */
  voorraadBeheerd?: boolean | null;
  voorraad?: number | null;
  huurprijs?: number | null;
  kostprijs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zoek op naam of e-mail; de klanthistorie staat op de evenementen van deze klant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klanten".
 */
export interface Klanten {
  id: number;
  naam: string;
  contactpersoon?: string | null;
  email?: string | null;
  telefoon?: string | null;
  adres?: {
    straat?: string | null;
    huisnummer?: string | null;
    postcode?: string | null;
    plaats?: string | null;
    land?: string | null;
  };
  factuuradres?: {
    straat?: string | null;
    huisnummer?: string | null;
    postcode?: string | null;
    plaats?: string | null;
    land?: string | null;
  };
  btwNummer?: string | null;
  /**
   * Interne notities, bv. dieetwensen uit eerdere evenementen.
   */
  notities?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Het aantal gasten drijft alle herberekening aan. Een wijziging werkt direct door in productie, inkoop en picking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenementen".
 */
export interface Evenementen {
  id: number;
  klant: number | Klanten;
  titel: string;
  datum: string;
  locatie?: string | null;
  /**
   * Het ene getal dat de hele keten herberekent.
   */
  aantalGasten: number;
  status: 'concept' | 'offerte_verzonden' | 'bevestigd' | 'in_productie' | 'geleverd' | 'gefactureerd' | 'afgerond';
  /**
   * Laat de overrides leeg om de productstandaard te gebruiken.
   */
  producten?:
    | {
        product: number | Producten;
        /**
         * Alleen als dit gerecht voor een deel van de gasten is.
         */
        aantalGastenOverride?: number | null;
        /**
         * Alleen als dit evenement een andere portie nodig heeft.
         */
        hoeveelheidPerPersoonOverride?: number | null;
        id?: string | null;
      }[]
    | null;
  materialen?:
    | {
        materiaal: number | Materialen;
        aantal: number;
        id?: string | null;
      }[]
    | null;
  notities?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Een offerte is een bevroren snapshot. Een latere prijswijziging verandert een verzonden offerte niet meer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offertes".
 */
export interface Offerte {
  id: number;
  event: number | Evenementen;
  versie: number;
  /**
   * Bevroren op het moment van genereren.
   */
  regels?:
    | {
        product?: string | null;
        productNaam?: string | null;
        aantalGasten?: number | null;
        hoeveelheidPerPersoon?: number | null;
        eenheid?: string | null;
        prijsPerPersoon?: number | null;
        btwTarief?: string | null;
        btwPercentage?: number | null;
        regelTotaalExcl?: number | null;
        btwBedrag?: number | null;
        regelTotaalIncl?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bevroren op het moment van aanmaken.
   */
  btwUitsplitsing?:
    | {
        btwTarief?: string | null;
        naam?: string | null;
        percentage?: number | null;
        grondslag?: number | null;
        btwBedrag?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotaal?: number | null;
  btwTotaal?: number | null;
  totaal?: number | null;
  status: 'concept' | 'verzonden' | 'geaccepteerd' | 'verlopen' | 'geweigerd';
  geldigTot: string;
  notities?: string | null;
  pdfBestand?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Een geaccepteerde offerte wordt een order: dezelfde data, nu definitief.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  event: number | Evenementen;
  offerte: number | Offerte;
  status: 'bevestigd' | 'in_productie' | 'gereed' | 'geleverd';
  bevestigingsdatum: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Het factuurnummer wordt automatisch toegekend en is oplopend zonder gaten — wettelijk verplicht en niet handmatig te wijzigen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facturen".
 */
export interface Facturen {
  id: number;
  order: number | Order;
  /**
   * Automatisch bepaald; nooit hergebruikt.
   */
  factuurnummer: string;
  factuurdatum: string;
  vervaldatum: string;
  /**
   * Bevroren op het moment van factureren.
   */
  regels?:
    | {
        omschrijving?: string | null;
        aantal?: number | null;
        eenheidsprijs?: number | null;
        btwTarief?: string | null;
        btwPercentage?: number | null;
        regelTotaalExcl?: number | null;
        btwBedrag?: number | null;
        regelTotaalIncl?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bevroren op het moment van aanmaken.
   */
  btwUitsplitsing?:
    | {
        btwTarief?: string | null;
        naam?: string | null;
        percentage?: number | null;
        grondslag?: number | null;
        btwBedrag?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotaal?: number | null;
  btwTotaal?: number | null;
  totaal?: number | null;
  status: 'concept' | 'verzonden' | 'betaald' | 'te_laat';
  /**
   * Een creditfactuur krijgt een eigen nieuw nummer; bestaande nummers blijven intact.
   */
  creditVan?: (number | null) | Facturen;
  pdfBestand?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * De order uitgesplitst tot recept- en ingrediëntniveau, geschaald naar gastenaantal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producties".
 */
export interface Producty {
  id: number;
  order: number | Order;
  /**
   * Automatisch berekend door de rekenmotor — niet handmatig aan te passen.
   */
  regels?:
    | {
        product?: string | null;
        productNaam?: string | null;
        recept?: string | null;
        receptNaam?: string | null;
        keukenstation?: string | null;
        aantalGasten?: number | null;
        hoeveelheidPerPersoon?: number | null;
        eenheid?: string | null;
        productHoeveelheid?: number | null;
        kostprijs?: number | null;
        ingredienten?:
          | {
              ingredient?: string | null;
              naam?: string | null;
              hoeveelheid?: number | null;
              basisEenheid?: string | null;
              kostprijs?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vrije instructies bovenop de gegenereerde productieregels.
   */
  keukenlijstNotities?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ingrediëntbehoefte over álle evenementen in de periode, gegroepeerd per leverancier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inkopen".
 */
export interface Inkopen {
  id: number;
  periodeVan: string;
  periodeTot: string;
  regels?:
    | {
        ingredient?: string | null;
        naam?: string | null;
        hoeveelheid?: number | null;
        inkoopEenheid?: string | null;
        eenheidsprijs?: number | null;
        kostprijs?: number | null;
        leverancier?: string | null;
        leverancierNaam?: string | null;
        herkomst?: string[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Voedsel uit de productie plus materialen uit het evenement, in één afvinkbare lijst.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickings".
 */
export interface Picking {
  id: number;
  order: number | Order;
  regels?:
    | {
        soort: 'voedsel' | 'materiaal';
        referentie?: string | null;
        omschrijving?: string | null;
        hoeveelheid?: number | null;
        eenheid?: string | null;
        afgevinkt?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status: 'open' | 'afgevinkt';
  afgevinktDoor?: (number | null) | Gebruiker;
  afgevinktOp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alleen de beheerder beheert gebruikers en rollen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers".
 */
export interface Gebruiker {
  id: number;
  naam: string;
  /**
   * Bepaalt welke onderdelen deze gebruiker mag zien en bewerken.
   */
  rol: 'beheerder' | 'verkoop' | 'keuken' | 'logistiek';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'gebruikers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leveringen".
 */
export interface Leveringen {
  id: number;
  order: number | Order;
  leverdatum: string;
  /**
   * Bv. 16:30.
   */
  levertijd: string;
  adres?: {
    straat?: string | null;
    huisnummer?: string | null;
    postcode?: string | null;
    plaats?: string | null;
    land?: string | null;
  };
  verantwoordelijke?: string | null;
  status: 'gepland' | 'onderweg' | 'geleverd';
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit trail van alle per e-mail verzonden documenten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verzendlog".
 */
export interface Verzendlog {
  id: number;
  event: number | Evenementen;
  documentType:
    | 'offerte'
    | 'orderbevestiging'
    | 'productielijst'
    | 'keukenlijst'
    | 'inkooplijst'
    | 'materialenlijst'
    | 'paklijst'
    | 'leveringslijst'
    | 'allergenenlijst'
    | 'factuur';
  ontvanger: string;
  onderwerp: string;
  verzondenOp: string;
  verzondenDoor: number | Gebruiker;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'producten';
        value: number | Producten;
      } | null)
    | ({
        relationTo: 'recepten';
        value: number | Recepten;
      } | null)
    | ({
        relationTo: 'ingredienten';
        value: number | Ingredienten;
      } | null)
    | ({
        relationTo: 'allergenen';
        value: number | Allergenen;
      } | null)
    | ({
        relationTo: 'btw-tarieven';
        value: number | BtwTarieven;
      } | null)
    | ({
        relationTo: 'categorieen';
        value: number | Categorieen;
      } | null)
    | ({
        relationTo: 'seizoenen';
        value: number | Seizoenen;
      } | null)
    | ({
        relationTo: 'leveranciers';
        value: number | Leverancier;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'klanten';
        value: number | Klanten;
      } | null)
    | ({
        relationTo: 'evenementen';
        value: number | Evenementen;
      } | null)
    | ({
        relationTo: 'materialen';
        value: number | Materialen;
      } | null)
    | ({
        relationTo: 'offertes';
        value: number | Offerte;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'facturen';
        value: number | Facturen;
      } | null)
    | ({
        relationTo: 'producties';
        value: number | Producty;
      } | null)
    | ({
        relationTo: 'inkopen';
        value: number | Inkopen;
      } | null)
    | ({
        relationTo: 'pickings';
        value: number | Picking;
      } | null)
    | ({
        relationTo: 'leveringen';
        value: number | Leveringen;
      } | null)
    | ({
        relationTo: 'gebruikers';
        value: number | Gebruiker;
      } | null)
    | ({
        relationTo: 'verzendlog';
        value: number | Verzendlog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producten_select".
 */
export interface ProductenSelect<T extends boolean = true> {
  naam?: T;
  beschrijving?: T;
  categorie?: T;
  fotos?: T;
  hoofdfoto?: T;
  portiesBasis?: T;
  eenheid?: T;
  hoeveelheidPerPersoon?: T;
  recept?: T;
  prijsPerPersoon?: T;
  btwTarief?: T;
  allergenen?: T;
  actief?: T;
  seizoen?: T;
  materialen?:
    | T
    | {
        materiaal?: T;
        hoeveelheid?: T;
        perAantalGasten?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recepten_select".
 */
export interface ReceptenSelect<T extends boolean = true> {
  naam?: T;
  basisPorties?: T;
  hoeveelheidPerPersoon?: T;
  eenheid?: T;
  ingredienten?:
    | T
    | {
        ingredient?: T;
        hoeveelheid?: T;
        eenheid?: T;
        id?: T;
      };
  bereidingswijze?: T;
  kooktijdMinuten?: T;
  keukenstation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredienten_select".
 */
export interface IngredientenSelect<T extends boolean = true> {
  naam?: T;
  inkoopeenheid?: T;
  inkoopprijs?: T;
  leverancier?: T;
  allergenen?: T;
  houdbaarheidDagen?: T;
  voorraad?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergenen_select".
 */
export interface AllergenenSelect<T extends boolean = true> {
  naam?: T;
  wettelijkeCode?: T;
  icoon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "btw-tarieven_select".
 */
export interface BtwTarievenSelect<T extends boolean = true> {
  naam?: T;
  percentage?: T;
  standaard?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorieen_select".
 */
export interface CategorieenSelect<T extends boolean = true> {
  naam?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seizoenen_select".
 */
export interface SeizoenenSelect<T extends boolean = true> {
  naam?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leveranciers_select".
 */
export interface LeveranciersSelect<T extends boolean = true> {
  naam?: T;
  contactpersoon?: T;
  email?: T;
  telefoon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altTekst?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'foodbook-card'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'foodbook-hero'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        print?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "klanten_select".
 */
export interface KlantenSelect<T extends boolean = true> {
  naam?: T;
  contactpersoon?: T;
  email?: T;
  telefoon?: T;
  adres?:
    | T
    | {
        straat?: T;
        huisnummer?: T;
        postcode?: T;
        plaats?: T;
        land?: T;
      };
  factuuradres?:
    | T
    | {
        straat?: T;
        huisnummer?: T;
        postcode?: T;
        plaats?: T;
        land?: T;
      };
  btwNummer?: T;
  notities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenementen_select".
 */
export interface EvenementenSelect<T extends boolean = true> {
  klant?: T;
  titel?: T;
  datum?: T;
  locatie?: T;
  aantalGasten?: T;
  status?: T;
  producten?:
    | T
    | {
        product?: T;
        aantalGastenOverride?: T;
        hoeveelheidPerPersoonOverride?: T;
        id?: T;
      };
  materialen?:
    | T
    | {
        materiaal?: T;
        aantal?: T;
        id?: T;
      };
  notities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materialen_select".
 */
export interface MaterialenSelect<T extends boolean = true> {
  naam?: T;
  eenheid?: T;
  voorraadBeheerd?: T;
  voorraad?: T;
  huurprijs?: T;
  kostprijs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offertes_select".
 */
export interface OffertesSelect<T extends boolean = true> {
  event?: T;
  versie?: T;
  regels?:
    | T
    | {
        product?: T;
        productNaam?: T;
        aantalGasten?: T;
        hoeveelheidPerPersoon?: T;
        eenheid?: T;
        prijsPerPersoon?: T;
        btwTarief?: T;
        btwPercentage?: T;
        regelTotaalExcl?: T;
        btwBedrag?: T;
        regelTotaalIncl?: T;
        id?: T;
      };
  btwUitsplitsing?:
    | T
    | {
        btwTarief?: T;
        naam?: T;
        percentage?: T;
        grondslag?: T;
        btwBedrag?: T;
        id?: T;
      };
  subtotaal?: T;
  btwTotaal?: T;
  totaal?: T;
  status?: T;
  geldigTot?: T;
  notities?: T;
  pdfBestand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  event?: T;
  offerte?: T;
  status?: T;
  bevestigingsdatum?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facturen_select".
 */
export interface FacturenSelect<T extends boolean = true> {
  order?: T;
  factuurnummer?: T;
  factuurdatum?: T;
  vervaldatum?: T;
  regels?:
    | T
    | {
        omschrijving?: T;
        aantal?: T;
        eenheidsprijs?: T;
        btwTarief?: T;
        btwPercentage?: T;
        regelTotaalExcl?: T;
        btwBedrag?: T;
        regelTotaalIncl?: T;
        id?: T;
      };
  btwUitsplitsing?:
    | T
    | {
        btwTarief?: T;
        naam?: T;
        percentage?: T;
        grondslag?: T;
        btwBedrag?: T;
        id?: T;
      };
  subtotaal?: T;
  btwTotaal?: T;
  totaal?: T;
  status?: T;
  creditVan?: T;
  pdfBestand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producties_select".
 */
export interface ProductiesSelect<T extends boolean = true> {
  order?: T;
  regels?:
    | T
    | {
        product?: T;
        productNaam?: T;
        recept?: T;
        receptNaam?: T;
        keukenstation?: T;
        aantalGasten?: T;
        hoeveelheidPerPersoon?: T;
        eenheid?: T;
        productHoeveelheid?: T;
        kostprijs?: T;
        ingredienten?:
          | T
          | {
              ingredient?: T;
              naam?: T;
              hoeveelheid?: T;
              basisEenheid?: T;
              kostprijs?: T;
              id?: T;
            };
        id?: T;
      };
  keukenlijstNotities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inkopen_select".
 */
export interface InkopenSelect<T extends boolean = true> {
  periodeVan?: T;
  periodeTot?: T;
  regels?:
    | T
    | {
        ingredient?: T;
        naam?: T;
        hoeveelheid?: T;
        inkoopEenheid?: T;
        eenheidsprijs?: T;
        kostprijs?: T;
        leverancier?: T;
        leverancierNaam?: T;
        herkomst?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickings_select".
 */
export interface PickingsSelect<T extends boolean = true> {
  order?: T;
  regels?:
    | T
    | {
        soort?: T;
        referentie?: T;
        omschrijving?: T;
        hoeveelheid?: T;
        eenheid?: T;
        afgevinkt?: T;
        id?: T;
      };
  status?: T;
  afgevinktDoor?: T;
  afgevinktOp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leveringen_select".
 */
export interface LeveringenSelect<T extends boolean = true> {
  order?: T;
  leverdatum?: T;
  levertijd?: T;
  adres?:
    | T
    | {
        straat?: T;
        huisnummer?: T;
        postcode?: T;
        plaats?: T;
        land?: T;
      };
  verantwoordelijke?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers_select".
 */
export interface GebruikersSelect<T extends boolean = true> {
  naam?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verzendlog_select".
 */
export interface VerzendlogSelect<T extends boolean = true> {
  event?: T;
  documentType?: T;
  ontvanger?: T;
  onderwerp?: T;
  verzondenOp?: T;
  verzondenDoor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, kleuren en juridische gegevens die op elk document terechtkomen. Door de beheerder zelf aan te passen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bedrijfsinstellingen".
 */
export interface Bedrijfsinstellingen {
  id: number;
  naam: string;
  logo?: (number | null) | Media;
  kvkNummer: string;
  btwNummer: string;
  iban: string;
  adres?: {
    straat?: string | null;
    huisnummer?: string | null;
    postcode?: string | null;
    plaats?: string | null;
    land?: string | null;
  };
  email: string;
  telefoon?: string | null;
  /**
   * Hexkleur, bv. #2f6564. Komt op de koppen van documenten.
   */
  primaireKleur: string;
  secundaireKleur: string;
  standaardVoettekst: string;
  /**
   * Bepaalt de vervaldatum van een factuur.
   */
  betalingstermijnDagen: number;
  offerteGeldigheidDagen: number;
  factuurPrefix: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bedrijfsinstellingen_select".
 */
export interface BedrijfsinstellingenSelect<T extends boolean = true> {
  naam?: T;
  logo?: T;
  kvkNummer?: T;
  btwNummer?: T;
  iban?: T;
  adres?:
    | T
    | {
        straat?: T;
        huisnummer?: T;
        postcode?: T;
        plaats?: T;
        land?: T;
      };
  email?: T;
  telefoon?: T;
  primaireKleur?: T;
  secundaireKleur?: T;
  standaardVoettekst?: T;
  betalingstermijnDagen?: T;
  offerteGeldigheidDagen?: T;
  factuurPrefix?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}